### ISSUE TITLE
Identify Hexbin

### ISSUE THREAD

**Issue by crvanpollard** [dvrpc/license-plate-survey#10]
Allow users to click on a hexbin and get a pop-up window with total commuter count for that hexbin

**Comment by rbeatty1** [comment]
Closed via e241187

**Comment by crvanpollard** [comment]
Pop-up window does not close when a user selects a new Station. 
Suggested Solution: Force pop-up to close once the Search Button has been fired
<img width="863" alt="screen shot 2018-12-05 at 9 36 10 am" src="https://user-images.githubusercontent.com/4401281/49520567-8ae42300-f871-11e8-8f7b-7a3a35617fca.png">
