### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by rbeatty1** [dvrpc/license-plate-survey#11]
Gotta make sure we keep track of whose using these things

**Comment by rbeatty1** [comment]
@mmolta wanna help me out with this one? I don't have any of our account jawns nor have I ever worked with GA. Just need to be pointed in the right direction

**Comment by mmolta** [comment]
ya sorry I should've included the script in the review notes. Here's the general jawn: 

<script>var _gaq = [['_setAccount', 'UA-9825778-1'], ['_trackPageview']];</script>
<script async src="//www.google-analytics.com/ga.js"></script> 

I *believe* the bracket that says ['_trackPageview'] can be edited to include other metrics you want but don't quote me on that.

Also it unfortunately has to go in your <head> after everything else and will bring down your Lighthouse performance score but that's cause elgoog skcus

**Comment by rbeatty1** [comment]
Closed with 9608d84
